<html>
  <head>
    <title>IdleRPG on <?php echo htmlspecialchars($this->getConfigurationValue('general', 'network', 'Darkmyst')); ?></title>
    <link rel="stylesheet" href="<?php
        echo htmlspecialchars(rtrim($this->getConfigurationValue('general', 'webroot'), '/'));
    ?>/assets/style.css" />
  </head>
  <body>

<h1>IdleRPG</h1>
<p><strong><?php echo htmlspecialchars($this->getConfigurationValue('botconf', 'botchan', '#IdleRPG')); ?> @ <?php

    $botconfServer = $this->getConfigurationValue('botconf', 'server', 'irc.darkmyst.org:6667');
    list($server) = explode(':', $botconfServer);
    echo htmlspecialchars($server);

?></strong></p>

    <nav>
      <ul>
<?php

$urls = array(
    '/'             => 'Game Info',
    '/players/list' => 'Player Info',
    '/map/view'     => 'World Map',
    '/quests/show'  => 'Quest Info',
);
$open = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);

foreach ($urls as $url => $label) {
    $url = $this->makeUrl($url);

    echo '<li';
    if ($url === $open) {
        echo ' class="selected"';
    }
    echo '><a href="' . htmlspecialchars($url) . '">' . htmlspecialchars($label) . '</a></li>';
}
?>
      </ul>
    </nav>

    <div class="content">
